// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/scoriadb.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxnOp_OpType int32

const (
	TxnOp_PUT    TxnOp_OpType = 0
	TxnOp_DELETE TxnOp_OpType = 1
)

// Enum value maps for TxnOp_OpType.
var (
	TxnOp_OpType_name = map[int32]string{
		0: "PUT",
		1: "DELETE",
	}
	TxnOp_OpType_value = map[string]int32{
		"PUT":    0,
		"DELETE": 1,
	}
)

func (x TxnOp_OpType) Enum() *TxnOp_OpType {
	p := new(TxnOp_OpType)
	*p = x
	return p
}

func (x TxnOp_OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TxnOp_OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_scoriadb_proto_enumTypes[0].Descriptor()
}

func (TxnOp_OpType) Type() protoreflect.EnumType {
	return &file_proto_scoriadb_proto_enumTypes[0]
}

func (x TxnOp_OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TxnOp_OpType.Descriptor instead.
func (TxnOp_OpType) EnumDescriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{10, 0}
}

// GetRequest contains key and optional column family name and snapshot timestamp.
type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CfName        string                 `protobuf:"bytes,2,opt,name=cf_name,json=cfName,proto3" json:"cf_name,omitempty"`
	SnapshotTs    int64                  `protobuf:"varint,3,opt,name=snapshot_ts,json=snapshotTs,proto3" json:"snapshot_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_scoriadb_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GetRequest) GetCfName() string {
	if x != nil {
		return x.CfName
	}
	return ""
}

func (x *GetRequest) GetSnapshotTs() int64 {
	if x != nil {
		return x.SnapshotTs
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         []byte                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_scoriadb_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	CfName        string                 `protobuf:"bytes,3,opt,name=cf_name,json=cfName,proto3" json:"cf_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_proto_scoriadb_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{2}
}

func (x *PutRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *PutRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *PutRequest) GetCfName() string {
	if x != nil {
		return x.CfName
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitTs      int64                  `protobuf:"varint,1,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_proto_scoriadb_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{3}
}

func (x *PutResponse) GetCommitTs() int64 {
	if x != nil {
		return x.CommitTs
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	CfName        string                 `protobuf:"bytes,2,opt,name=cf_name,json=cfName,proto3" json:"cf_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_scoriadb_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DeleteRequest) GetCfName() string {
	if x != nil {
		return x.CfName
	}
	return ""
}

type DeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommitTs      int64                  `protobuf:"varint,1,opt,name=commit_ts,json=commitTs,proto3" json:"commit_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_proto_scoriadb_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteResponse) GetCommitTs() int64 {
	if x != nil {
		return x.CommitTs
	}
	return 0
}

type ScanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        []byte                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	CfName        string                 `protobuf:"bytes,2,opt,name=cf_name,json=cfName,proto3" json:"cf_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanRequest) Reset() {
	*x = ScanRequest{}
	mi := &file_proto_scoriadb_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanRequest) ProtoMessage() {}

func (x *ScanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanRequest.ProtoReflect.Descriptor instead.
func (*ScanRequest) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{6}
}

func (x *ScanRequest) GetPrefix() []byte {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *ScanRequest) GetCfName() string {
	if x != nil {
		return x.CfName
	}
	return ""
}

type ScanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScanResponse) Reset() {
	*x = ScanResponse{}
	mi := &file_proto_scoriadb_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanResponse) ProtoMessage() {}

func (x *ScanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScanResponse.ProtoReflect.Descriptor instead.
func (*ScanResponse) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{7}
}

func (x *ScanResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *ScanResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// Transaction messages
type BeginTxnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTxnRequest) Reset() {
	*x = BeginTxnRequest{}
	mi := &file_proto_scoriadb_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTxnRequest) ProtoMessage() {}

func (x *BeginTxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTxnRequest.ProtoReflect.Descriptor instead.
func (*BeginTxnRequest) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{8}
}

type BeginTxnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	StartTs       int64                  `protobuf:"varint,2,opt,name=start_ts,json=startTs,proto3" json:"start_ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginTxnResponse) Reset() {
	*x = BeginTxnResponse{}
	mi := &file_proto_scoriadb_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTxnResponse) ProtoMessage() {}

func (x *BeginTxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTxnResponse.ProtoReflect.Descriptor instead.
func (*BeginTxnResponse) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{9}
}

func (x *BeginTxnResponse) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *BeginTxnResponse) GetStartTs() int64 {
	if x != nil {
		return x.StartTs
	}
	return 0
}

type TxnOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            TxnOp_OpType           `protobuf:"varint,1,opt,name=op,proto3,enum=scoriadb.TxnOp_OpType" json:"op,omitempty"`
	Key           []byte                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         []byte                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	CfName        string                 `protobuf:"bytes,4,opt,name=cf_name,json=cfName,proto3" json:"cf_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxnOp) Reset() {
	*x = TxnOp{}
	mi := &file_proto_scoriadb_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxnOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxnOp) ProtoMessage() {}

func (x *TxnOp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxnOp.ProtoReflect.Descriptor instead.
func (*TxnOp) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{10}
}

func (x *TxnOp) GetOp() TxnOp_OpType {
	if x != nil {
		return x.Op
	}
	return TxnOp_PUT
}

func (x *TxnOp) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *TxnOp) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TxnOp) GetCfName() string {
	if x != nil {
		return x.CfName
	}
	return ""
}

type CommitTxnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	Ops           []*TxnOp               `protobuf:"bytes,2,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTxnRequest) Reset() {
	*x = CommitTxnRequest{}
	mi := &file_proto_scoriadb_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxnRequest) ProtoMessage() {}

func (x *CommitTxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxnRequest.ProtoReflect.Descriptor instead.
func (*CommitTxnRequest) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{11}
}

func (x *CommitTxnRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

func (x *CommitTxnRequest) GetOps() []*TxnOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

type CommitTxnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitTxnResponse) Reset() {
	*x = CommitTxnResponse{}
	mi := &file_proto_scoriadb_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitTxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitTxnResponse) ProtoMessage() {}

func (x *CommitTxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitTxnResponse.ProtoReflect.Descriptor instead.
func (*CommitTxnResponse) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{12}
}

type RollbackTxnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnId         string                 `protobuf:"bytes,1,opt,name=txn_id,json=txnId,proto3" json:"txn_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTxnRequest) Reset() {
	*x = RollbackTxnRequest{}
	mi := &file_proto_scoriadb_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTxnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTxnRequest) ProtoMessage() {}

func (x *RollbackTxnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTxnRequest.ProtoReflect.Descriptor instead.
func (*RollbackTxnRequest) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{13}
}

func (x *RollbackTxnRequest) GetTxnId() string {
	if x != nil {
		return x.TxnId
	}
	return ""
}

type RollbackTxnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackTxnResponse) Reset() {
	*x = RollbackTxnResponse{}
	mi := &file_proto_scoriadb_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackTxnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackTxnResponse) ProtoMessage() {}

func (x *RollbackTxnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackTxnResponse.ProtoReflect.Descriptor instead.
func (*RollbackTxnResponse) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{14}
}

// User management messages
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_proto_scoriadb_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{15}
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_proto_scoriadb_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{16}
}

type AuthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_proto_scoriadb_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{17}
}

func (x *AuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JwtToken      string                 `protobuf:"bytes,1,opt,name=jwt_token,json=jwtToken,proto3" json:"jwt_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_proto_scoriadb_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scoriadb_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_proto_scoriadb_proto_rawDescGZIP(), []int{18}
}

func (x *AuthResponse) GetJwtToken() string {
	if x != nil {
		return x.JwtToken
	}
	return ""
}

var File_proto_scoriadb_proto protoreflect.FileDescriptor

const file_proto_scoriadb_proto_rawDesc = "" +
	"\n" +
	"\x14proto/scoriadb.proto\x12\bscoriadb\"X\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x17\n" +
	"\acf_name\x18\x02 \x01(\tR\x06cfName\x12\x1f\n" +
	"\vsnapshot_ts\x18\x03 \x01(\x03R\n" +
	"snapshotTs\"9\n" +
	"\vGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\fR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"M\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x17\n" +
	"\acf_name\x18\x03 \x01(\tR\x06cfName\"*\n" +
	"\vPutResponse\x12\x1b\n" +
	"\tcommit_ts\x18\x01 \x01(\x03R\bcommitTs\":\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x17\n" +
	"\acf_name\x18\x02 \x01(\tR\x06cfName\"-\n" +
	"\x0eDeleteResponse\x12\x1b\n" +
	"\tcommit_ts\x18\x01 \x01(\x03R\bcommitTs\">\n" +
	"\vScanRequest\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\fR\x06prefix\x12\x17\n" +
	"\acf_name\x18\x02 \x01(\tR\x06cfName\"6\n" +
	"\fScanResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"\x11\n" +
	"\x0fBeginTxnRequest\"D\n" +
	"\x10BeginTxnResponse\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12\x19\n" +
	"\bstart_ts\x18\x02 \x01(\x03R\astartTs\"\x8f\x01\n" +
	"\x05TxnOp\x12&\n" +
	"\x02op\x18\x01 \x01(\x0e2\x16.scoriadb.TxnOp.OpTypeR\x02op\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\fR\x05value\x12\x17\n" +
	"\acf_name\x18\x04 \x01(\tR\x06cfName\"\x1d\n" +
	"\x06OpType\x12\a\n" +
	"\x03PUT\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\"L\n" +
	"\x10CommitTxnRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\x12!\n" +
	"\x03ops\x18\x02 \x03(\v2\x0f.scoriadb.TxnOpR\x03ops\"\x13\n" +
	"\x11CommitTxnResponse\"+\n" +
	"\x12RollbackTxnRequest\x12\x15\n" +
	"\x06txn_id\x18\x01 \x01(\tR\x05txnId\"\x15\n" +
	"\x13RollbackTxnResponse\"a\n" +
	"\x11CreateUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\"\x14\n" +
	"\x12CreateUserResponse\"E\n" +
	"\vAuthRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\fAuthResponse\x12\x1b\n" +
	"\tjwt_token\x18\x01 \x01(\tR\bjwtToken2\xc5\x04\n" +
	"\bScoriaDB\x122\n" +
	"\x03Get\x12\x14.scoriadb.GetRequest\x1a\x15.scoriadb.GetResponse\x122\n" +
	"\x03Put\x12\x14.scoriadb.PutRequest\x1a\x15.scoriadb.PutResponse\x12;\n" +
	"\x06Delete\x12\x17.scoriadb.DeleteRequest\x1a\x18.scoriadb.DeleteResponse\x127\n" +
	"\x04Scan\x12\x15.scoriadb.ScanRequest\x1a\x16.scoriadb.ScanResponse0\x01\x12A\n" +
	"\bBeginTxn\x12\x19.scoriadb.BeginTxnRequest\x1a\x1a.scoriadb.BeginTxnResponse\x12D\n" +
	"\tCommitTxn\x12\x1a.scoriadb.CommitTxnRequest\x1a\x1b.scoriadb.CommitTxnResponse\x12J\n" +
	"\vRollbackTxn\x12\x1c.scoriadb.RollbackTxnRequest\x1a\x1d.scoriadb.RollbackTxnResponse\x12G\n" +
	"\n" +
	"CreateUser\x12\x1b.scoriadb.CreateUserRequest\x1a\x1c.scoriadb.CreateUserResponse\x12=\n" +
	"\fAuthenticate\x12\x15.scoriadb.AuthRequest\x1a\x16.scoriadb.AuthResponseB\x10Z\x0escoriadb/protob\x06proto3"

var (
	file_proto_scoriadb_proto_rawDescOnce sync.Once
	file_proto_scoriadb_proto_rawDescData []byte
)

func file_proto_scoriadb_proto_rawDescGZIP() []byte {
	file_proto_scoriadb_proto_rawDescOnce.Do(func() {
		file_proto_scoriadb_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scoriadb_proto_rawDesc), len(file_proto_scoriadb_proto_rawDesc)))
	})
	return file_proto_scoriadb_proto_rawDescData
}

var file_proto_scoriadb_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_scoriadb_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_proto_scoriadb_proto_goTypes = []any{
	(TxnOp_OpType)(0),           // 0: scoriadb.TxnOp.OpType
	(*GetRequest)(nil),          // 1: scoriadb.GetRequest
	(*GetResponse)(nil),         // 2: scoriadb.GetResponse
	(*PutRequest)(nil),          // 3: scoriadb.PutRequest
	(*PutResponse)(nil),         // 4: scoriadb.PutResponse
	(*DeleteRequest)(nil),       // 5: scoriadb.DeleteRequest
	(*DeleteResponse)(nil),      // 6: scoriadb.DeleteResponse
	(*ScanRequest)(nil),         // 7: scoriadb.ScanRequest
	(*ScanResponse)(nil),        // 8: scoriadb.ScanResponse
	(*BeginTxnRequest)(nil),     // 9: scoriadb.BeginTxnRequest
	(*BeginTxnResponse)(nil),    // 10: scoriadb.BeginTxnResponse
	(*TxnOp)(nil),               // 11: scoriadb.TxnOp
	(*CommitTxnRequest)(nil),    // 12: scoriadb.CommitTxnRequest
	(*CommitTxnResponse)(nil),   // 13: scoriadb.CommitTxnResponse
	(*RollbackTxnRequest)(nil),  // 14: scoriadb.RollbackTxnRequest
	(*RollbackTxnResponse)(nil), // 15: scoriadb.RollbackTxnResponse
	(*CreateUserRequest)(nil),   // 16: scoriadb.CreateUserRequest
	(*CreateUserResponse)(nil),  // 17: scoriadb.CreateUserResponse
	(*AuthRequest)(nil),         // 18: scoriadb.AuthRequest
	(*AuthResponse)(nil),        // 19: scoriadb.AuthResponse
}
var file_proto_scoriadb_proto_depIdxs = []int32{
	0,  // 0: scoriadb.TxnOp.op:type_name -> scoriadb.TxnOp.OpType
	11, // 1: scoriadb.CommitTxnRequest.ops:type_name -> scoriadb.TxnOp
	1,  // 2: scoriadb.ScoriaDB.Get:input_type -> scoriadb.GetRequest
	3,  // 3: scoriadb.ScoriaDB.Put:input_type -> scoriadb.PutRequest
	5,  // 4: scoriadb.ScoriaDB.Delete:input_type -> scoriadb.DeleteRequest
	7,  // 5: scoriadb.ScoriaDB.Scan:input_type -> scoriadb.ScanRequest
	9,  // 6: scoriadb.ScoriaDB.BeginTxn:input_type -> scoriadb.BeginTxnRequest
	12, // 7: scoriadb.ScoriaDB.CommitTxn:input_type -> scoriadb.CommitTxnRequest
	14, // 8: scoriadb.ScoriaDB.RollbackTxn:input_type -> scoriadb.RollbackTxnRequest
	16, // 9: scoriadb.ScoriaDB.CreateUser:input_type -> scoriadb.CreateUserRequest
	18, // 10: scoriadb.ScoriaDB.Authenticate:input_type -> scoriadb.AuthRequest
	2,  // 11: scoriadb.ScoriaDB.Get:output_type -> scoriadb.GetResponse
	4,  // 12: scoriadb.ScoriaDB.Put:output_type -> scoriadb.PutResponse
	6,  // 13: scoriadb.ScoriaDB.Delete:output_type -> scoriadb.DeleteResponse
	8,  // 14: scoriadb.ScoriaDB.Scan:output_type -> scoriadb.ScanResponse
	10, // 15: scoriadb.ScoriaDB.BeginTxn:output_type -> scoriadb.BeginTxnResponse
	13, // 16: scoriadb.ScoriaDB.CommitTxn:output_type -> scoriadb.CommitTxnResponse
	15, // 17: scoriadb.ScoriaDB.RollbackTxn:output_type -> scoriadb.RollbackTxnResponse
	17, // 18: scoriadb.ScoriaDB.CreateUser:output_type -> scoriadb.CreateUserResponse
	19, // 19: scoriadb.ScoriaDB.Authenticate:output_type -> scoriadb.AuthResponse
	11, // [11:20] is the sub-list for method output_type
	2,  // [2:11] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_scoriadb_proto_init() }
func file_proto_scoriadb_proto_init() {
	if File_proto_scoriadb_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scoriadb_proto_rawDesc), len(file_proto_scoriadb_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scoriadb_proto_goTypes,
		DependencyIndexes: file_proto_scoriadb_proto_depIdxs,
		EnumInfos:         file_proto_scoriadb_proto_enumTypes,
		MessageInfos:      file_proto_scoriadb_proto_msgTypes,
	}.Build()
	File_proto_scoriadb_proto = out.File
	file_proto_scoriadb_proto_goTypes = nil
	file_proto_scoriadb_proto_depIdxs = nil
}
