// Copyright 2026 Ekaterina Godulyan
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/scoriadb.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScoriaDB_Get_FullMethodName            = "/scoriadb.ScoriaDB/Get"
	ScoriaDB_Put_FullMethodName            = "/scoriadb.ScoriaDB/Put"
	ScoriaDB_Delete_FullMethodName         = "/scoriadb.ScoriaDB/Delete"
	ScoriaDB_Scan_FullMethodName           = "/scoriadb.ScoriaDB/Scan"
	ScoriaDB_ListCFs_FullMethodName        = "/scoriadb.ScoriaDB/ListCFs"
	ScoriaDB_CreateCF_FullMethodName       = "/scoriadb.ScoriaDB/CreateCF"
	ScoriaDB_DeleteCF_FullMethodName       = "/scoriadb.ScoriaDB/DeleteCF"
	ScoriaDB_UseCF_FullMethodName          = "/scoriadb.ScoriaDB/UseCF"
	ScoriaDB_BeginTxn_FullMethodName       = "/scoriadb.ScoriaDB/BeginTxn"
	ScoriaDB_CommitTxn_FullMethodName      = "/scoriadb.ScoriaDB/CommitTxn"
	ScoriaDB_RollbackTxn_FullMethodName    = "/scoriadb.ScoriaDB/RollbackTxn"
	ScoriaDB_CreateUser_FullMethodName     = "/scoriadb.ScoriaDB/CreateUser"
	ScoriaDB_Authenticate_FullMethodName   = "/scoriadb.ScoriaDB/Authenticate"
	ScoriaDB_ChangePassword_FullMethodName = "/scoriadb.ScoriaDB/ChangePassword"
)

// ScoriaDBClient is the client API for ScoriaDB service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ScoriaDB gRPC service
type ScoriaDBClient interface {
	// Basic KV operations
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanResponse], error)
	// Column Family operations
	ListCFs(ctx context.Context, in *ListCFsRequest, opts ...grpc.CallOption) (*ListCFsResponse, error)
	CreateCF(ctx context.Context, in *CreateCFRequest, opts ...grpc.CallOption) (*CreateCFResponse, error)
	DeleteCF(ctx context.Context, in *DeleteCFRequest, opts ...grpc.CallOption) (*DeleteCFResponse, error)
	UseCF(ctx context.Context, in *UseCFRequest, opts ...grpc.CallOption) (*UseCFResponse, error)
	// Transaction operations
	BeginTxn(ctx context.Context, in *BeginTxnRequest, opts ...grpc.CallOption) (*BeginTxnResponse, error)
	CommitTxn(ctx context.Context, in *CommitTxnRequest, opts ...grpc.CallOption) (*CommitTxnResponse, error)
	RollbackTxn(ctx context.Context, in *RollbackTxnRequest, opts ...grpc.CallOption) (*RollbackTxnResponse, error)
	// Authentication and user management
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error)
}

type scoriaDBClient struct {
	cc grpc.ClientConnInterface
}

func NewScoriaDBClient(cc grpc.ClientConnInterface) ScoriaDBClient {
	return &scoriaDBClient{cc}
}

func (c *scoriaDBClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoriaDBClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoriaDBClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoriaDBClient) Scan(ctx context.Context, in *ScanRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScanResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ScoriaDB_ServiceDesc.Streams[0], ScoriaDB_Scan_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScanRequest, ScanResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScoriaDB_ScanClient = grpc.ServerStreamingClient[ScanResponse]

func (c *scoriaDBClient) ListCFs(ctx context.Context, in *ListCFsRequest, opts ...grpc.CallOption) (*ListCFsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCFsResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_ListCFs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoriaDBClient) CreateCF(ctx context.Context, in *CreateCFRequest, opts ...grpc.CallOption) (*CreateCFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCFResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_CreateCF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoriaDBClient) DeleteCF(ctx context.Context, in *DeleteCFRequest, opts ...grpc.CallOption) (*DeleteCFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCFResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_DeleteCF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoriaDBClient) UseCF(ctx context.Context, in *UseCFRequest, opts ...grpc.CallOption) (*UseCFResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseCFResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_UseCF_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoriaDBClient) BeginTxn(ctx context.Context, in *BeginTxnRequest, opts ...grpc.CallOption) (*BeginTxnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginTxnResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_BeginTxn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoriaDBClient) CommitTxn(ctx context.Context, in *CommitTxnRequest, opts ...grpc.CallOption) (*CommitTxnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitTxnResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_CommitTxn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoriaDBClient) RollbackTxn(ctx context.Context, in *RollbackTxnRequest, opts ...grpc.CallOption) (*RollbackTxnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackTxnResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_RollbackTxn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoriaDBClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoriaDBClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_Authenticate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scoriaDBClient) ChangePassword(ctx context.Context, in *ChangePasswordRequest, opts ...grpc.CallOption) (*ChangePasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePasswordResponse)
	err := c.cc.Invoke(ctx, ScoriaDB_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScoriaDBServer is the server API for ScoriaDB service.
// All implementations must embed UnimplementedScoriaDBServer
// for forward compatibility.
//
// ScoriaDB gRPC service
type ScoriaDBServer interface {
	// Basic KV operations
	Get(context.Context, *GetRequest) (*GetResponse, error)
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	Scan(*ScanRequest, grpc.ServerStreamingServer[ScanResponse]) error
	// Column Family operations
	ListCFs(context.Context, *ListCFsRequest) (*ListCFsResponse, error)
	CreateCF(context.Context, *CreateCFRequest) (*CreateCFResponse, error)
	DeleteCF(context.Context, *DeleteCFRequest) (*DeleteCFResponse, error)
	UseCF(context.Context, *UseCFRequest) (*UseCFResponse, error)
	// Transaction operations
	BeginTxn(context.Context, *BeginTxnRequest) (*BeginTxnResponse, error)
	CommitTxn(context.Context, *CommitTxnRequest) (*CommitTxnResponse, error)
	RollbackTxn(context.Context, *RollbackTxnRequest) (*RollbackTxnResponse, error)
	// Authentication and user management
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error)
	mustEmbedUnimplementedScoriaDBServer()
}

// UnimplementedScoriaDBServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScoriaDBServer struct{}

func (UnimplementedScoriaDBServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedScoriaDBServer) Put(context.Context, *PutRequest) (*PutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedScoriaDBServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedScoriaDBServer) Scan(*ScanRequest, grpc.ServerStreamingServer[ScanResponse]) error {
	return status.Error(codes.Unimplemented, "method Scan not implemented")
}
func (UnimplementedScoriaDBServer) ListCFs(context.Context, *ListCFsRequest) (*ListCFsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCFs not implemented")
}
func (UnimplementedScoriaDBServer) CreateCF(context.Context, *CreateCFRequest) (*CreateCFResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCF not implemented")
}
func (UnimplementedScoriaDBServer) DeleteCF(context.Context, *DeleteCFRequest) (*DeleteCFResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCF not implemented")
}
func (UnimplementedScoriaDBServer) UseCF(context.Context, *UseCFRequest) (*UseCFResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UseCF not implemented")
}
func (UnimplementedScoriaDBServer) BeginTxn(context.Context, *BeginTxnRequest) (*BeginTxnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginTxn not implemented")
}
func (UnimplementedScoriaDBServer) CommitTxn(context.Context, *CommitTxnRequest) (*CommitTxnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitTxn not implemented")
}
func (UnimplementedScoriaDBServer) RollbackTxn(context.Context, *RollbackTxnRequest) (*RollbackTxnResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackTxn not implemented")
}
func (UnimplementedScoriaDBServer) CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUser not implemented")
}
func (UnimplementedScoriaDBServer) Authenticate(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedScoriaDBServer) ChangePassword(context.Context, *ChangePasswordRequest) (*ChangePasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedScoriaDBServer) mustEmbedUnimplementedScoriaDBServer() {}
func (UnimplementedScoriaDBServer) testEmbeddedByValue()                  {}

// UnsafeScoriaDBServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScoriaDBServer will
// result in compilation errors.
type UnsafeScoriaDBServer interface {
	mustEmbedUnimplementedScoriaDBServer()
}

func RegisterScoriaDBServer(s grpc.ServiceRegistrar, srv ScoriaDBServer) {
	// If the following call panics, it indicates UnimplementedScoriaDBServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScoriaDB_ServiceDesc, srv)
}

func _ScoriaDB_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoriaDB_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoriaDB_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoriaDB_Scan_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScanRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ScoriaDBServer).Scan(m, &grpc.GenericServerStream[ScanRequest, ScanResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ScoriaDB_ScanServer = grpc.ServerStreamingServer[ScanResponse]

func _ScoriaDB_ListCFs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCFsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).ListCFs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_ListCFs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).ListCFs(ctx, req.(*ListCFsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoriaDB_CreateCF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).CreateCF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_CreateCF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).CreateCF(ctx, req.(*CreateCFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoriaDB_DeleteCF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).DeleteCF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_DeleteCF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).DeleteCF(ctx, req.(*DeleteCFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoriaDB_UseCF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseCFRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).UseCF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_UseCF_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).UseCF(ctx, req.(*UseCFRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoriaDB_BeginTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).BeginTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_BeginTxn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).BeginTxn(ctx, req.(*BeginTxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoriaDB_CommitTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).CommitTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_CommitTxn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).CommitTxn(ctx, req.(*CommitTxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoriaDB_RollbackTxn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackTxnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).RollbackTxn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_RollbackTxn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).RollbackTxn(ctx, req.(*RollbackTxnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoriaDB_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_CreateUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoriaDB_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_Authenticate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScoriaDB_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScoriaDBServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScoriaDB_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScoriaDBServer).ChangePassword(ctx, req.(*ChangePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScoriaDB_ServiceDesc is the grpc.ServiceDesc for ScoriaDB service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScoriaDB_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scoriadb.ScoriaDB",
	HandlerType: (*ScoriaDBServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _ScoriaDB_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _ScoriaDB_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ScoriaDB_Delete_Handler,
		},
		{
			MethodName: "ListCFs",
			Handler:    _ScoriaDB_ListCFs_Handler,
		},
		{
			MethodName: "CreateCF",
			Handler:    _ScoriaDB_CreateCF_Handler,
		},
		{
			MethodName: "DeleteCF",
			Handler:    _ScoriaDB_DeleteCF_Handler,
		},
		{
			MethodName: "UseCF",
			Handler:    _ScoriaDB_UseCF_Handler,
		},
		{
			MethodName: "BeginTxn",
			Handler:    _ScoriaDB_BeginTxn_Handler,
		},
		{
			MethodName: "CommitTxn",
			Handler:    _ScoriaDB_CommitTxn_Handler,
		},
		{
			MethodName: "RollbackTxn",
			Handler:    _ScoriaDB_RollbackTxn_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _ScoriaDB_CreateUser_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _ScoriaDB_Authenticate_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _ScoriaDB_ChangePassword_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Scan",
			Handler:       _ScoriaDB_Scan_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/scoriadb.proto",
}
